name: Unit Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm Install
      - name: Run unit Tests
        run: npm run test
